apiVersion: v1
kind: Service
metadata:
  name: leak-detector-service
  namespace: leak-detector
  labels:
    app: leak-detector
spec:
  type: LoadBalancer
  selector:
    app: leak-detector
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
